<div class="container">
    <div class="row" data-gutter="60">
        <div class="col-md-6 col-md-offset-3">
            <h3>Connexion</h3>

            <?php if (isset($isLoginError)): ?>
                <div class="alert alert-danger">Error login</div>
            <?php endif; ?>

            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('user', array('controller' => 'login', 'action' => 'process')));
                $form->prepare();
                echo $this->form()->openTag($form);
            ?>

            <div class="form-group form-group-icon-left"><i
                    class="fa fa-user input-icon input-icon-show"></i>
                <label>Username or email</label>
                <?php echo $this->formelement($form->get('email')); ?>
                <?php echo $this->formelementerrors($form->get('email')); ?>
            </div>

            <div class="form-group form-group-icon-left"><i
                    class="fa fa-lock input-icon input-icon-show"></i>
                <label>Password</label>
                <?php echo $this->formelement($form->get('password')); ?>
                <?php echo $this->formelementerrors($form->get('password')); ?>
            </div>

            <input type="submit" value="Login" class="btn color medium full"/>
            <?php echo $this->form()->closeTag(); ?>
            <a href="<?= $this->url('contact') ?>">
                Contactez nous
            </a>
        </div>
    </div>
</div>