<div class="container">
    <div class="row" data-gutter="60">
        <div class="col-md-6">
            <h3>Connexion el comparador</h3>
            <p>
                Gagnez du temps et bénéficiez de tarifs attractifs grâce aux nombreux services
                touristiques proposés sur notre plateforme.
            </p>
        </div>

        <div class="col-md-6">
            <h3>Login</h3>
            <?php if (isset($isLoginError)): ?>
                <div class="alert alert-danger">Error login</div>
            <?php endif; ?>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('user', array('controller' => 'login', 'action' => 'process')));
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group form-group-icon-left"><i class="fa fa-user input-icon input-icon-show"></i>
                <label>Username or email</label>
                <?php echo $this->formelement($form->get('email')); ?>
                <?php echo $this->formelementerrors($form->get('email')); ?>
            </div>
            <div class="form-group form-group-icon-left"><i class="fa fa-lock input-icon input-icon-show"></i>
                <label>Password</label>
                <?php echo $this->formelement($form->get('password')); ?>
                <?php echo $this->formelementerrors($form->get('password')); ?>
            </div>
            <input type="submit" value="Login" class="btn color medium full"/>
            <?php echo $this->form()->closeTag(); ?>
            <a href="#">Forgotten password?</a><br/>Pas encore inscrit?
            <a href="<?= $this->url('user', array('controller' => 'register')) ?>">inscription ICI </a>
        </div>
    </div>
</div>