<div class="container">

    <h3>Update Password</h3>

    <div class="row">

        <div class="col-md-3">
            <?= $this->sidebar_helper() ?>
        </div>
        <div class="col-lg-4">

            <?php if ($this->successChanged === false): ?>
                <div class="alert alert-danger">
                    les mot de passe ne sans pas les meme
                </div>
            <?php endif; ?>

            <?= $this->successChanged?>

            <?php if ($this->successChanged === true): ?>
                <div class="alert alert-success">
                    mot de passe mise a jour avec succées
                </div>
            <?php endif; ?>

            <?php
            $form = $this->form;
            $form->setAttribute("action", $this->url('board/user', ["controller" => "update-password", "action" => "process"]));
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-group form-group-icon-left">
                <i class="fa fa-lock input-icon input-icon-show"></i>
                <label>Password</label>
                <?php echo $this->formelement($form->get('password')); ?>
                <?php echo $this->formelementerrors($form->get('password')); ?>
            </div>
            <div class="form-group form-group-icon-left">
                <i class="fa fa-lock input-icon input-icon-show"></i>
                <label>Password</label>
                <?php echo $this->formelement($form->get('confirm_password')); ?>
                <?php echo $this->formelementerrors($form->get('confirm_password')); ?>
            </div>
            <input type="submit" value="Envoyer"
                   class="btn btn-primary"/>
            <?php echo $this->form()->closeTag(); ?>

        </div>


    </div>

</div>