<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
        'strategies' => array(
            'ViewJsonStrategy',
        ),
    ),

    'controllers' => array(
        'invokables'=>[
            'Api\Controller\Position'=>'Api\Controller\PositionController'
        ],
    ),

    'router' => array(
        'routes' => array(
            'api' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/api',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Api\Controller',
                        'controller' => 'Position',
                    ),
                ),
            ),
        ),
        'may_terminate' => true,
        'child_routes' => array(
            'position' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/position[/:id]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    ),
                    'defaults'=>[
                        'controller'=>'Api\Controller\Position',
                        'action'=>'index',
                    ],
                ),
            ),
        ),
    ),
);