<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
        'strategies' => array(
            'ViewJsonStrategy',
        ),
    ),
    'controllers' => array(
        'invokables' => [
            'Api\Controller\Position' => 'Api\Controller\PositionController',
            'Api\Controller\NewPosition' => 'Api\Controller\NewPositionController',
        ],
    ),

    'router' => array(
        'routes' => array(
            'position' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/api/position',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Api\Controller',
                        'controller' => 'Position',
                    ),
                ),
            ),
            'new-position' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/api/new-position',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Api\Controller',
                        'controller' => 'NewPosition',
                    ),
                ),
            ),
        ),
    ),
);