<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
    'controllers' => [],

    'service_manager' => [
        'invokables'=>[
            'Common\Listeners\ApiProblemListener'=>'Common\Listeners\ApiProblemListener',
            'Common\Listeners\Authorization'=>'Common\Listeners\Authorization',
        ]
    ],
    'router' => []
);